name = "nowhere-to-park-worker"
main = "index.ts"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]

[vars]
ALLOWED_ORIGIN = "https://nowhere-to-park.pages.dev,https://nowhere-to-park.nikhilrajaram.dev"
PMTILE_FILENAME = "parking.pmtiles"